modules:
- ant
- core/compiler.common.native
- core/compiler.common.js
- core/descriptors.runtime
- core/metadata.jvm
- core/deserialization.common
- core/compiler.common.wasm
- core/util.runtime
- core/descriptors
- core/deserialization.common.jvm
- core/descriptors.jvm
- core/compiler.common
- core/compiler.common.jvm
- core/metadata
- core/deserialization
- core/compiler.common.web
- analysis/analysis-api-platform-interface
- analysis/decompiled/light-classes-for-decompiled
- analysis/decompiled/decompiler-to-psi
- analysis/decompiled/decompiler-to-stubs
- analysis/decompiled/decompiler-js
- analysis/decompiled/decompiler-to-file-stubs
- analysis/decompiled/decompiler-native
- analysis/symbol-light-classes
- analysis/analysis-api-fir
- analysis/analysis-api-fir/analysis-api-fir-generator
- analysis/low-level-api-fir/tests-jdk11
- analysis/low-level-api-fir
- analysis/analysis-internal-utils
- analysis/analysis-test-framework
- analysis/analysis-tools/deprecated-k1-frontend-internals-for-ide-generated
- analysis/analysis-tools/deprecated-k1-frontend-internals-for-ide-generator
- analysis/analysis-api-impl-base
- analysis/light-classes-base
- analysis/analysis-api-standalone
- analysis/analysis-api-standalone/analysis-api-standalone-base
- analysis/analysis-api-standalone/analysis-api-fir-standalone-base
- analysis/kt-references
- analysis
- analysis/analysis-api-fe10
- analysis/analysis-api
- native/analysis-api-klib-reader
- native/frontend-native
- native/utils
- native/executors
- native/swift/sir-printer
- native/swift
- native/swift/sir-compiler-bridge
- native/swift/sir/tree-generator-native
- native/swift/sir
- native/swift/swift-export-ide
- native/swift/swift-export-standalone
- native/swift/sir-providers
- native/swift/swift-export-embeddable
- native/swift/sir-light-classes
- native/base
- prepare/compiler-client-embeddable
- prepare/analysis-api-test-framework
- prepare/kotlin-daemon-embeddable
- prepare/compiler-embeddable
- prepare/kotlin-jps-plugin
- prepare/android-extensions-compiler-gradle
- prepare/parcelize-compiler-gradle
- prepare/compiler-prepare
- prepare/kotlin-compiler-internal-test-framework
- plugins/atomicfu/atomicfu-compiler-embeddable
- plugins/atomicfu/atomicfu-compiler
- plugins/jvm-abi-gen/embeddable
- plugins/jvm-abi-gen
#- plugins/plugins-interactions-testing
- plugins/parcelize/parcelize-compiler/parcelize.k2
- plugins/parcelize/parcelize-compiler
- plugins/parcelize/parcelize-compiler/parcelize.k1
- plugins/parcelize/parcelize-compiler/parcelize.common
- plugins/parcelize/parcelize-compiler/parcelize.backend
- plugins/parcelize/parcelize-compiler/parcelize.cli
- plugins/parcelize/parcelize-runtime
- plugins/scripting/scripting-compiler-impl
- plugins/scripting/scripting-compiler
#- plugins/scripting/test-script-definition
- plugins/scripting/scripting-ide-services-embeddable
- plugins/scripting/scripting-compiler-embeddable
- plugins/scripting/scripting-compiler-impl-embeddable
- plugins/scripting/scripting-ide-services-test
#- plugins/scripting/scripting-tests
- plugins/scripting/scripting-ide-common
- plugins/scripting/scripting-ide-services
- plugins/assign-plugin/assign-plugin.common
- plugins/assign-plugin/assign-plugin.k1
- plugins/assign-plugin/assign-plugin.k2
#- plugins/assign-plugin
- plugins/assign-plugin/assign-plugin.cli
- plugins/assign-plugin/assign-plugin.embeddable
- plugins/power-assert/power-assert.backend
#- plugins/power-assert
- plugins/power-assert/power-assert.cli
- plugins/power-assert/power-assert.embeddable
- plugins/lombok
- plugins/lombok/lombok.embeddable
- plugins/lombok/lombok.k1
- plugins/lombok/lombok.cli
- plugins/lombok/lombok.common
- plugins/lombok/lombok.k2
- plugins/imports-dumper
- plugins/kotlinx-serialization/kotlinx-serialization.embeddable
- plugins/kotlinx-serialization/kotlinx-serialization.cli
- plugins/kotlinx-serialization/kotlinx-serialization.k1
- plugins/kotlinx-serialization
- plugins/kotlinx-serialization/kotlinx-serialization.common
- plugins/kotlinx-serialization/kotlinx-serialization.backend
- plugins/kotlinx-serialization/kotlinx-serialization.k2
- plugins/plugin-sandbox/plugin-sandbox-ic-test
- plugins/plugin-sandbox
- plugins/noarg/noarg.cli
- plugins/noarg/noarg.k1
- plugins/noarg/noarg.backend
#- plugins/noarg
- plugins/noarg/noarg.embeddable
- plugins/noarg/noarg.k2
- plugins/noarg/noarg.common
#- plugins/kapt4
#- plugins/kapt3/kotlin-annotation-processing-embeddable
#- plugins/kapt3/kapt3-base
#- plugins/kapt3/kapt3-runtime
#- plugins/kapt3/kapt3-cli
#- plugins/kapt3/kapt3-compiler
- plugins/sam-with-receiver/sam-with-receiver.common
- plugins/sam-with-receiver/sam-with-receiver.k2
- plugins/sam-with-receiver/sam-with-receiver.embeddable
- plugins/sam-with-receiver/sam-with-receiver.cli
#- plugins/sam-with-receiver
- plugins/sam-with-receiver/sam-with-receiver.k1
#- plugins/pill/pill-importer
#- plugins/pill/generate-all-tests
- plugins/android-extensions/android-extensions-compiler
- plugins/android-extensions/android-extensions-runtime
- plugins/js-plain-objects/compiler-plugin/js-plain-objects.cli
- plugins/js-plain-objects/compiler-plugin
- plugins/js-plain-objects/compiler-plugin/js-plain-objects.k2
- plugins/js-plain-objects/compiler-plugin/js-plain-objects.backend
- plugins/js-plain-objects/compiler-plugin/js-plain-objects.common
- plugins/js-plain-objects/compiler-plugin-embeddable
- plugins/allopen/allopen.embeddable
- plugins/allopen/allopen.k2
#- plugins/allopen
- plugins/allopen/allopen.k1
- plugins/allopen/allopen.common
- plugins/allopen/allopen.cli
- js/js.config
- js/js.parser
- js/js.sourcemap
- js/js.frontend
- js/js.ast
- js/js.serializer
#- js/js.tests/klib-compatibility
#- js/js.tests
- js/js.translator
- wasm/wasm.config
#- wasm/wasm.tests
- wasm/wasm.ir
- wasm/wasm.frontend
#- jps/jps-plugin
- jps/jps-platform-api-signatures
- jps/jps-common
- dependencies/intellij-core
- libraries/tools/kotlin-tooling-core
- libraries/tools/kotlinp/kotlinp-jvm
- libraries/tools/kotlinp
- libraries/tools/kotlinp/kotlinp-klib
- libraries/tools/kotlin-annotations-jvm
- libraries/tools/kotlin-build-tools-enum-compat
- libraries/tools/abi-comparator
- libraries/tools/kotlin-gradle-compiler-types
#- libraries/scripting/jsr223-test
- libraries/scripting/dependencies-maven
- libraries/scripting/scripting-jvm
- libraries/scripting/dependencies
- libraries/scripting/common
#- libraries/scripting/jvm-host-test
- libraries/scripting/jsr223
- libraries/scripting/jsr223-embeddable
- libraries/scripting/intellij
- libraries/scripting/jvm-host
- libraries/scripting/jvm-host-embeddable
- libraries/reflect
- libraries/reflect/api
- libraries/kotlinx-metadata/metadata-jvm
- libraries/kotlinx-metadata
- libraries/kotlinx-metadata/klib
#- benchmarks
- generators
- generators/test-generator
- generators/analysis-api-generator
- generators/ide-iml-to-gradle-generator
- generators/tree-generator-common
- compiler/frontend.common
- compiler/compiler.version
- compiler/test-infrastructure
- compiler/compiler-runner-unshaded
- compiler/preloader
- compiler/backend.common.jvm
- compiler/util-klib-abi
- compiler/backend-common
- compiler/fir/tree/tree-generator-fir
- compiler/fir/tree
- compiler/fir/checkers/checkers-component-generator
- compiler/fir/checkers/checkers.native
- compiler/fir/checkers/checkers.js
- compiler/fir/checkers/checkers.web.common
- compiler/fir/checkers/checkers.wasm
- compiler/fir/checkers
- compiler/fir/checkers/checkers.jvm
- compiler/fir/dump
- compiler/fir/analysis-tests/legacy-fir-tests
- compiler/fir/analysis-tests
- compiler/fir/native
- compiler/fir/resolve
- compiler/fir/fir-deserialization
- compiler/fir/providers
- compiler/fir/java
- compiler/fir/semantics
- compiler/fir/fir2ir/jvm-backend
- compiler/fir/fir2ir
- compiler/fir/fir-entrypoint
- compiler/fir/cones
- compiler/fir/plugin-utils
- compiler/fir/raw-fir/light-tree2fir
- compiler/fir/raw-fir/raw-fir.common
- compiler/fir/raw-fir/psi2fir
- compiler/fir/fir-serialization
- compiler/fir/modularized-tests
- compiler/resolution.common.jvm
- compiler/frontend
- compiler/frontend/cfg
- compiler/javac-wrapper
- compiler/util
- compiler/config
- compiler/config/configuration-keys-generator
- compiler/compiler-runner
- compiler/ir/ir.objcinterop
- compiler/ir/backend.wasm
- compiler/ir/ir.interpreter
- compiler/ir/backend.common
- compiler/ir/serialization.jvm
- compiler/ir/serialization.common
- compiler/ir/ir.inline
- compiler/ir/backend.js
- compiler/ir/ir.psi2ir
- compiler/ir/serialization.js
- compiler/ir/ir.tree/tree-generator
- compiler/ir/ir.tree
- compiler/ir/serialization.native
- compiler/ir/backend.jvm/codegen
- compiler/ir/backend.jvm/entrypoint
- compiler/ir/backend.jvm/lower
- compiler/ir/backend.jvm
- compiler/ir/ir.actualization
- compiler/tests-common-new
- compiler/util-io
- compiler/light-classes
- compiler/serialization
- compiler/tests-against-klib
- compiler/config.jvm
- compiler/backend
- compiler/cli/cli-base
- compiler/cli/cli-common
- compiler/cli/cli-js
- compiler/cli/cli-runner
- compiler/cli
- compiler/plugin-api
- compiler/tests-for-compiler-generator
- compiler/util-klib
- compiler/container
- compiler/tests-java8
- compiler/resolution
- compiler/daemon/daemon-client
- compiler/daemon/daemon-common
#- compiler/daemon/daemon-tests
- compiler/daemon
- compiler/tests-different-jdk
- compiler/tests-integration
- compiler/frontend.common-psi
- compiler/frontend.java
- compiler/test-infrastructure-utils
- compiler/tests-common
- compiler/tests-spec
- compiler/util-klib-metadata
- compiler/psi
- compiler/tests-mutes/mutes-junit5
- compiler/tests-mutes/tc-integration
- compiler/tests-mutes/mutes-junit4
- compiler/tests-mutes
- compiler/android-tests
- compiler/incremental-compilation-impl
- compiler/resolution.common
- compiler/tests-compiler-utils
- compiler/build-tools/kotlin-build-tools-jdk-utils
- compiler/build-tools/kotlin-build-statistics
- compiler/build-tools/kotlin-build-tools-api
- compiler/build-tools/kotlin-build-tools-impl
- compiler
- compiler/frontend.common.jvm
- build-common
- repo/codebase-tests
#- repo/artifacts-tests
- test-instrumenter
